name: Check External Repo for Changes

on:
  schedule:
    - cron: "0,30 * * * *" # Runs at 00 and 30 minutes past every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  check-repo-updates:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    env:
      STATE_FILE: ".github/last_commit_phpservermon_phpservermon_develop.txt" # Globally defined state file

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest commit from external repository
        if: success() # Executes the step only if the previous step was successful
        run: |
          REPO_OWNER="phpservermon"
          REPO_NAME="phpservermon"
          BRANCH="develop"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"

          # Retrieve the latest commit from the external repository
          LATEST_COMMIT=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/commits/$BRANCH" | jq -r '.sha')

          echo "Latest commit: $LATEST_COMMIT"

          # Check if a previous commit ID is stored
          if [ -f $STATE_FILE ]; then
            LAST_SAVED_COMMIT=$(cat $STATE_FILE)
            echo "Last stored commit: $LAST_SAVED_COMMIT"

            if [ "$LATEST_COMMIT" == "$LAST_SAVED_COMMIT" ]; then
              echo "No new commits found. Exiting workflow."
              exit 78
            fi
          fi

          # If a new commit is detected, save it
          echo $LATEST_COMMIT > $STATE_FILE
          echo "New commit detected! Triggering update state file."

      - name: Commit and push updated state file
        if: success() # Executes the step only if the previous step was successful
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add $STATE_FILE

          # Check if there are changes to commit
          if git diff --cached --exit-code > /dev/null; then
            echo "No changes detected. Skipping commit and push."
            exit 78
          fi

          git commit -m "Update last commit state file of root repo phpservermonitor"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}

      - name: Trigger Deployment Workflow
        if: success() # Executes the step only if the previous step was successful
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docker-publish.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          ref: master  # used branch
